In [1]:
import pandas as pd

In [2]:
def get_mean(df):
    counts = df.groupby('pred_label').size()
    ratios = counts / len(df)
    result = pd.concat([counts, ratios], axis=1, keys=['count', 'ratio'])
    return result

In [3]:
csv_file = "test_model_output-bfs.txt"
df = pd.read_csv(csv_file,sep='|')
get_mean(df)

            count     ratio
pred_label
DEEPFAKE     2756  0.279882
REAL         7091  0.720118

In [4]:
csv_file = "test_model_output_iso_aligned_vh_df_bfs_1.txt"
df = pd.read_csv(csv_file,sep='|')
get_mean(df)

            count     ratio
pred_label
DEEPFAKE     6914  0.702143
REAL         2933  0.297857

In [7]:
csv_file = "test_model_output_processed_vh_df_ghostface_1.txt"
df = pd.read_csv(csv_file,sep='|')
get_mean(df)

            count     ratio
pred_label
DEEPFAKE     9840  0.998985
REAL           10  0.001015

In [11]:
csv_file = "test_model_output_processed_vh_df_heser_1.txt"
df = pd.read_csv(csv_file,sep='|')
get_mean(df)

            count     ratio
pred_label
DEEPFAKE     9834  0.998781
REAL           12  0.001219

In [12]:
csv_file = "test_model_output_iso_aligned_vh_df_heser_1.txt"
df = pd.read_csv(csv_file,sep='|')
get_mean(df)

            count     ratio
pred_label
DEEPFAKE     9843  0.999695
REAL            3  0.000305

In [14]:
csv_file = "test_model_output_processed_vh_df_instyleswapper_1.txt"
df = pd.read_csv(csv_file,sep='|')
print(get_mean(df))

csv_file = "test_model_output_iso_aligned_vh_df_instyleswapper_1.txt"
df = pd.read_csv(csv_file,sep='|')
print(get_mean(df))

            count     ratio
pred_label
DEEPFAKE     9818  0.996954
REAL           30  0.003046
            count     ratio
pred_label
DEEPFAKE     9834  0.998578
REAL           14  0.001422

In [ ]:
csv_file = "test_model_output_iso_aligned_vh_df_reface__1.txt"
df = pd.read_csv(csv_file,sep='|')
get_mean(df)

FileNotFoundError: [Errno 2] No such file or directory: 'test_model_output_iso_aligned_vh_df_reface_1.txt'